### ISSUE TITLE
list_templates returns binary type in python 3

### ISSUE THREAD

**Issue by RogerHaase** [liuliqiang/flask-theme#1]
We are using flask-theme for https://github.com/moinwiki/moin

When doing a port to Python 3 we encvountered an error caused by a list of mixed strings and bytes. The problem seems to be in this code:

    def list_templates(self):
        res = []
        ctx = _request_ctx_stack.top
        fmt = '_themes/%s/%s'
        for ident, theme in ctx.app.theme_manager.themes.items():
            # ~ res.extend((fmt % (ident, t)).encode("utf-8")
            res.extend((fmt % (ident, t))
                       for t in theme.jinja_loader.list_templates())
        return res

where the error is in the commented out line and corrected in the line below it. The encode creates a byte type in python 3. 

    Traceback (most recent call last):
      File "C:\git37\moin-venv-python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
        response = self.full_dispatch_request()
      File "C:\git37\moin-venv-python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "C:\git37\moin-venv-python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "C:\git37\moin-venv-python\lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "C:\git37\moin-venv-python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
        rv = self.dispatch_request()
      File "C:\git37\moin-venv-python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "c:\git37\moin\src\moin\apps\frontend\views.py", line 506, in show_item
        result = item.do_show(rev)
      File "c:\git37\moin\src\moin\items\__init__.py", line 994, in do_show
        html_head_meta=html_head_meta,
      File "c:\git37\moin\src\moin\themes\__init__.py", line 58, in render_template
        return render_theme_template(get_current_theme(), template, **context)
      File "C:\git37\moin-venv-python\lib\site-packages\flask_theme\__init__.py", line 471, in render_theme_template
        return render_template(template_name, **context)
      File "C:\git37\moin-venv-python\lib\site-packages\flask\templating.py", line 140, in render_template
        ctx.app,
      File "C:\git37\moin-venv-python\lib\site-packages\flask\templating.py", line 120, in _render
        rv = template.render(context)
      File "C:\git37\moin-venv-python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "C:\git37\moin-venv-python\lib\site-packages\jinja2\environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "C:\git37\moin-venv-python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "C:\git37\moin-venv-python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "c:\git37\moin\src\moin\templates\show.html", line 1, in top-level template code
        {% extends theme("layout.html") %}
      File "C:\git37\moin-venv-python\lib\site-packages\flask_theme\__init__.py", line 420, in global_theme_template
        if (not fallback) or template_exists(templatepath):
      File "C:\git37\moin-venv-python\lib\site-packages\flask_theme\__init__.py", line 354, in template_exists
        return templatename in containable(ctx.app.jinja_env.list_templates())
      File "C:\git37\moin-venv-python\lib\site-packages\jinja2\environment.py", line 749, in list_templates
        x = self.loader.list_templates()
      File "C:\git37\moin-venv-python\lib\site-packages\jinja2\loaders.py", line 414, in list_templates
        return sorted(found)
    TypeError: '<' not supported between instances of 'bytes' and 'str'

I lightly tested the above change with our python 2 code. Removal of the encode had no adverse effect.

**Comment by ThomasWaldmann** [comment]
I could reproduce the issue and tried the fix. Works for me on py35 also.

**Comment by liuliqiang** [comment]
would you mind to take a fix? @ThomasWaldmann ,currently，i have no plan for  py3 support。

**Comment by ThomasWaldmann** [comment]
Working on a PR...

**Comment by ThomasWaldmann** [comment]
thanks for merging!
